/**
 * Created by aliyy on 2017/1/14.
 */
import React, { Component } from 'react'
import {connect} from 'react-redux'
import selectBook from '../actions/index'
// 要引入bindActionCreators
// this is the function that binds action creaters right here,
// is where we going to use to make sure that the action that is generated by the action creater
// actually ends up flowing through all the different reducers
// so this is the part right here where we take that return value from selectBook and
// make sure that actually flows through all the different reducers in our application
import {bindActionCreators} from 'redux'

class BookList extends Component{
  renderList(){
    //以下return写法注意
    return this.props.books.map((book)=>{
      //这里也得写return
      return(
        <li
          className="list-group-item"
          key={book.title}
          onClick={()=>this.props.selectBook(book)}
        >
          {book.title}
        </li>
      )
    })
  }

  render(){
    return (
      <ul className="col-sm-4 list-group">
        {/*此处调用renderList方法*/}
        {this.renderList()}
      </ul>
    )
  }
}

//此处需要写function关键字，方法名是固定的
function mapStateToProps(state){
  //此处需要return一个对象
  return {
    //whatever is returned will show up as props inside of BookList
    books: state.books    //此处的state.books会返回到组件的props.books中
  }
}

// anything returned from this function will end up as props on the BookList container
// if we call this.props.selectBook in our container, the action creater selectBook will be called.
function mapDispatchToProps(dispatch) {
  //要写return，bindActionCreators把selectBook这个action creater, dispatch到每个reducer里
  // whenever selectBook is called, the result should be passed to all of our reducers(through dispatch)
  // that was what bindActionCreators with dispatch doing here
  return bindActionCreators({selectBook: selectBook}, dispatch)
//  上面的value selectBook只是一个plain function，如果我们直接调用，返回的只是一个普通对象
//  我们需要把selectBook传到reducers中，只有reducers care about this action(selectBook)
//  so the purpose of bindActionCreators and dispatch is specifically to take what gets returned from selectBook
//  and make sure it flows through all the reducers
}

// Promote BookList from a component to a container -
// it needs to know about this new dispatch method, selectBook.
// make it available as a prop
export default connect(mapStateToProps, mapDispatchToProps)(BookList)














